# fly.toml app configuration file generated for velocity-manager on 2023-12-24T14:27:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "velocity-manager"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
